// tests/runtime-integration.test.ts - integration checks for installed hook commands.
// These tests execute the command strings generated by feynman install, using
// isolated HOME directories so the real ~/.claude and ~/.codex are never touched.

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

const REPO_DIR = path.resolve(import.meta.dirname, '..');
const FEYNMAN_JS = path.join(REPO_DIR, 'bin', 'feynman.ts');

function makeTempHome(): string {
  return fs.mkdtempSync(path.join(os.tmpdir(), 'feynman-runtime-int-'));
}

function rmrf(dir: string): void {
  try { fs.rmSync(dir, { recursive: true, force: true }); } catch (_) {}
}

function runFeynman(tmpHome: string, args: string[]): { status: number; stdout: string; stderr: string } {
  const result = spawnSync(process.execPath, [FEYNMAN_JS, ...args], {
    cwd: REPO_DIR,
    encoding: 'utf8',
    env: {
      ...process.env,
      HOME: tmpHome,
      NO_COLOR: '1',
    },
  });
  return {
    status: result.status ?? 1,
    stdout: result.stdout || '',
    stderr: result.stderr || '',
  };
}

function readJson(file: string): Record<string, unknown> {
  return JSON.parse(fs.readFileSync(file, 'utf8'));
}

function readRuntimeConfig(tmpHome: string, target: string): Record<string, unknown> {
  const file = target === 'codex'
    ? path.join(tmpHome, '.codex', 'hooks.json')
    : path.join(tmpHome, '.claude', 'settings.json');
  return readJson(file);
}

function runtimeHome(tmpHome: string, target: string): string {
  return path.join(tmpHome, target === 'codex' ? '.codex' : '.claude');
}

function findHookCommand(config: Record<string, unknown>, eventName: string, scriptName: string): string {
  const hooksMap = config['hooks'] as Record<string, { hooks: { command: string }[] }[]> | undefined;
  const groups = (hooksMap && hooksMap[eventName]) || [];
  for (const group of groups) {
    for (const hook of group.hooks || []) {
      if (hook.command && hook.command.includes(scriptName)) {
        return hook.command;
      }
    }
  }
  assert.fail(`${scriptName} command not found in ${eventName}`);
}

function runConfiguredHook(tmpHome: string, command: string, stdin: unknown): { status: number; stdout: string; stderr: string } {
  const result = spawnSync(command, [], {
    cwd: REPO_DIR,
    shell: true,
    input: JSON.stringify(stdin),
    encoding: 'utf8',
    env: {
      ...process.env,
      HOME: tmpHome,
      NO_COLOR: '1',
    },
    timeout: 10000,
  });
  return {
    status: result.status ?? 1,
    stdout: result.stdout || '',
    stderr: result.stderr || '',
  };
}

function parsePromptHookOutput(stdout: string): string {
  const parsed = JSON.parse(stdout);
  assert.ok(parsed.hookSpecificOutput, 'hookSpecificOutput missing');
  assert.equal(parsed.hookSpecificOutput.hookEventName, 'UserPromptSubmit');
  assert.equal(typeof parsed.hookSpecificOutput.additionalContext, 'string');
  return parsed.hookSpecificOutput.additionalContext;
}

describe('installed Feynman hook command integration', () => {
  it('runs generated Claude Code and Codex hook commands end-to-end', () => {
    const tmpHome = makeTempHome();
    try {
      const install = runFeynman(tmpHome, ['install', '--target', 'both', '--force']);
      assert.equal(install.status, 0, `install failed: ${install.stderr}`);

      for (const target of ['claude', 'codex']) {
        const config = readRuntimeConfig(tmpHome, target);
        const sessionCommand = findHookCommand(
          config,
          'SessionStart',
          'feynman-session-start.ts'
        );
        const promptCommand = findHookCommand(
          config,
          'UserPromptSubmit',
          'feynman-activate.ts'
        );

        assert.ok(sessionCommand.includes(`FEYNMAN_HOME="${runtimeHome(tmpHome, target)}"`));
        assert.ok(promptCommand.includes(`FEYNMAN_HOME="${runtimeHome(tmpHome, target)}"`));

        const session = runConfiguredHook(tmpHome, sessionCommand, {
          hook_event_name: 'SessionStart',
          session_id: `${target}-session`,
        });
        assert.equal(session.status, 0, `${target} SessionStart exited non-zero`);
        assert.equal(session.stderr, '', `${target} SessionStart stderr: ${session.stderr}`);
        assert.ok(
          /<triggers>|<contract>|→|├──/.test(session.stdout),
          `${target} SessionStart should emit rule-file diagram tokens`
        );

        const prompt = runConfiguredHook(tmpHome, promptCommand, {
          session_id: `${target}-session`,
          prompt: 'Explain deploy pipeline stages.',
        });
        assert.equal(prompt.status, 0, `${target} UserPromptSubmit exited non-zero`);
        assert.equal(prompt.stderr, '', `${target} UserPromptSubmit stderr: ${prompt.stderr}`);
        assert.equal(prompt.stdout.endsWith('\n'), false, `${target} prompt hook must avoid trailing newline`);

        const context = parsePromptHookOutput(prompt.stdout);
        assert.ok(
          /<triggers>|<contract>|→|├──/.test(context),
          `${target} additionalContext should contain rule-file diagram tokens`
        );

        const state = readJson(path.join(runtimeHome(tmpHome, target), '.feynman', 'state.json'));
        assert.equal(state['enabled'], true);
        assert.equal(state['intensity'], 'full');
        assert.equal(state['injections'], 1, `${target} prompt hook should increment injections once`);
      }
    } finally {
      rmrf(tmpHome);
    }
  });

  it('runs installed Codex hooks silently when disabled', () => {
    const tmpHome = makeTempHome();
    try {
      const install = runFeynman(tmpHome, ['install', '--target', 'codex', '--force']);
      assert.equal(install.status, 0, `install failed: ${install.stderr}`);

      const codexHome = runtimeHome(tmpHome, 'codex');
      fs.writeFileSync(
        path.join(codexHome, '.feynman', 'state.json'),
        JSON.stringify({ enabled: false, intensity: 'full', injections: 7 }, null, 2)
      );
      fs.rmSync(path.join(codexHome, '.feynman-active'), { force: true });

      const config = readRuntimeConfig(tmpHome, 'codex');
      const sessionCommand = findHookCommand(config, 'SessionStart', 'feynman-session-start.ts');
      const promptCommand = findHookCommand(config, 'UserPromptSubmit', 'feynman-activate.ts');

      const session = runConfiguredHook(tmpHome, sessionCommand, {
        hook_event_name: 'SessionStart',
        session_id: 'disabled-session',
      });
      assert.equal(session.status, 0);
      assert.equal(session.stdout, '');
      assert.equal(session.stderr, '');

      const prompt = runConfiguredHook(tmpHome, promptCommand, {
        session_id: 'disabled-session',
        prompt: 'Explain deploy pipeline stages.',
      });
      assert.equal(prompt.status, 0);
      assert.equal(prompt.stdout, '');
      assert.equal(prompt.stderr, '');

      const state = readJson(path.join(codexHome, '.feynman', 'state.json'));
      assert.equal(state['enabled'], false);
      assert.equal(state['injections'], 7);
      assert.equal(fs.existsSync(path.join(codexHome, '.feynman-active')), false);
    } finally {
      rmrf(tmpHome);
    }
  });
});
