// tests/runtime-integration.test.js - integration checks for installed hook commands.
// These tests execute the command strings generated by feynman install, using
// isolated HOME directories so the real ~/.claude and ~/.codex are never touched.
'use strict';

const { describe, it } = require('node:test');
const assert = require('node:assert/strict');
const { spawnSync } = require('node:child_process');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

const REPO_DIR = path.resolve(__dirname, '..');
const FEYNMAN_JS = path.join(REPO_DIR, 'bin', 'feynman.js');

function makeTempHome() {
  return fs.mkdtempSync(path.join(os.tmpdir(), 'feynman-runtime-int-'));
}

function rmrf(dir) {
  try { fs.rmSync(dir, { recursive: true, force: true }); } catch (_) {}
}

function runFeynman(tmpHome, args) {
  const result = spawnSync(process.execPath, [FEYNMAN_JS, ...args], {
    cwd: REPO_DIR,
    encoding: 'utf8',
    env: {
      ...process.env,
      HOME: tmpHome,
      NO_COLOR: '1',
    },
  });
  return {
    status: result.status ?? 1,
    stdout: result.stdout || '',
    stderr: result.stderr || '',
  };
}

function readJson(file) {
  return JSON.parse(fs.readFileSync(file, 'utf8'));
}

function readRuntimeConfig(tmpHome, target) {
  const file = target === 'codex'
    ? path.join(tmpHome, '.codex', 'hooks.json')
    : path.join(tmpHome, '.claude', 'settings.json');
  return readJson(file);
}

function runtimeHome(tmpHome, target) {
  return path.join(tmpHome, target === 'codex' ? '.codex' : '.claude');
}

function findHookCommand(config, eventName, scriptName) {
  const groups = (config.hooks && config.hooks[eventName]) || [];
  for (const group of groups) {
    for (const hook of group.hooks || []) {
      if (hook.command && hook.command.includes(scriptName)) {
        return hook.command;
      }
    }
  }
  assert.fail(`${scriptName} command not found in ${eventName}`);
}

function runConfiguredHook(tmpHome, command, stdin) {
  const result = spawnSync(command, [], {
    cwd: REPO_DIR,
    shell: true,
    input: JSON.stringify(stdin),
    encoding: 'utf8',
    env: {
      ...process.env,
      HOME: tmpHome,
      NO_COLOR: '1',
    },
    timeout: 10000,
  });
  return {
    status: result.status ?? 1,
    stdout: result.stdout || '',
    stderr: result.stderr || '',
  };
}

function parsePromptHookOutput(stdout) {
  const parsed = JSON.parse(stdout);
  assert.ok(parsed.hookSpecificOutput, 'hookSpecificOutput missing');
  assert.equal(parsed.hookSpecificOutput.hookEventName, 'UserPromptSubmit');
  assert.equal(typeof parsed.hookSpecificOutput.additionalContext, 'string');
  return parsed.hookSpecificOutput.additionalContext;
}

describe('installed Feynman hook command integration', () => {
  it('runs generated Claude Code and Codex hook commands end-to-end', () => {
    const tmpHome = makeTempHome();
    try {
      const install = runFeynman(tmpHome, ['install', '--target', 'both', '--force']);
      assert.equal(install.status, 0, `install failed: ${install.stderr}`);

      for (const target of ['claude', 'codex']) {
        const config = readRuntimeConfig(tmpHome, target);
        const sessionCommand = findHookCommand(
          config,
          'SessionStart',
          'feynman-session-start.js'
        );
        const promptCommand = findHookCommand(
          config,
          'UserPromptSubmit',
          'feynman-activate.js'
        );

        assert.ok(sessionCommand.includes(`FEYNMAN_HOME="${runtimeHome(tmpHome, target)}"`));
        assert.ok(promptCommand.includes(`FEYNMAN_HOME="${runtimeHome(tmpHome, target)}"`));

        const session = runConfiguredHook(tmpHome, sessionCommand, {
          hook_event_name: 'SessionStart',
          session_id: `${target}-session`,
        });
        assert.equal(session.status, 0, `${target} SessionStart exited non-zero`);
        assert.equal(session.stderr, '', `${target} SessionStart stderr: ${session.stderr}`);
        assert.ok(
          session.stdout.includes('Feynman Diagram Rules'),
          `${target} SessionStart should emit rules text`
        );

        const prompt = runConfiguredHook(tmpHome, promptCommand, {
          session_id: `${target}-session`,
          prompt: 'Explain deploy pipeline stages.',
        });
        assert.equal(prompt.status, 0, `${target} UserPromptSubmit exited non-zero`);
        assert.equal(prompt.stderr, '', `${target} UserPromptSubmit stderr: ${prompt.stderr}`);
        assert.equal(prompt.stdout.endsWith('\n'), false, `${target} prompt hook must avoid trailing newline`);

        const context = parsePromptHookOutput(prompt.stdout);
        assert.ok(
          context.includes('Feynman Diagram Rules'),
          `${target} additionalContext should contain diagram rules`
        );

        const state = readJson(path.join(runtimeHome(tmpHome, target), '.feynman', 'state.json'));
        assert.equal(state.enabled, true);
        assert.equal(state.intensity, 'full');
        assert.equal(state.injections, 1, `${target} prompt hook should increment injections once`);
      }
    } finally {
      rmrf(tmpHome);
    }
  });

  it('runs installed Codex hooks silently when disabled', () => {
    const tmpHome = makeTempHome();
    try {
      const install = runFeynman(tmpHome, ['install', '--target', 'codex', '--force']);
      assert.equal(install.status, 0, `install failed: ${install.stderr}`);

      const codexHome = runtimeHome(tmpHome, 'codex');
      fs.writeFileSync(
        path.join(codexHome, '.feynman', 'state.json'),
        JSON.stringify({ enabled: false, intensity: 'full', injections: 7 }, null, 2)
      );
      fs.rmSync(path.join(codexHome, '.feynman-active'), { force: true });

      const config = readRuntimeConfig(tmpHome, 'codex');
      const sessionCommand = findHookCommand(config, 'SessionStart', 'feynman-session-start.js');
      const promptCommand = findHookCommand(config, 'UserPromptSubmit', 'feynman-activate.js');

      const session = runConfiguredHook(tmpHome, sessionCommand, {
        hook_event_name: 'SessionStart',
        session_id: 'disabled-session',
      });
      assert.equal(session.status, 0);
      assert.equal(session.stdout, '');
      assert.equal(session.stderr, '');

      const prompt = runConfiguredHook(tmpHome, promptCommand, {
        session_id: 'disabled-session',
        prompt: 'Explain deploy pipeline stages.',
      });
      assert.equal(prompt.status, 0);
      assert.equal(prompt.stdout, '');
      assert.equal(prompt.stderr, '');

      const state = readJson(path.join(codexHome, '.feynman', 'state.json'));
      assert.equal(state.enabled, false);
      assert.equal(state.injections, 7);
      assert.equal(fs.existsSync(path.join(codexHome, '.feynman-active')), false);
    } finally {
      rmrf(tmpHome);
    }
  });
});
